# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 欢迎来到我的小世界
description: ''
keywords:
author: Jasmine
language: zh-CN
timezone: Asia/Shanghai

# 副标题
# 主页subtitle
subtitle:
  enable: true
  # Typewriter Effect (打字效果)
  effect: true
  # 如果关闭打字效果，subtitle 只会显示 sub 的第一行文字
  sub:
    - 看见雪停，我便猜是你要到了。 ——Zayne

#theme_color:
enable: true
main: "#8aabd9"

#
avatar:
  img: /image/b_396d2c65c6d973a43d310f09a53bcdb8.jpg
  # effect: true 会一直转

#social:
fa-github: https://github.com/Jasmine661 || fab

#nav:
logo: /image/b_396d2c65c6d973a43d310f09a53bcdb8.jpg
display_title: true
fixed: false # fixed navigation bar    
menu:
  首页: / || fas fa-home
  时间轴: /archives/ || fas fa-archive
  标签: /tags/ || fas fa-tags
  分类: /categories/ || fas fa-folder-open
  清单||fa fa-heartbeat:
    音乐: /music/ || fas fa-music
    照片: /Gallery/ || fas fa-images
    电影: /movies/ || fas fa-video

#顶部图
index_img: /image/header2.jpg #默认顶部图
default_top_img: /image/微信图片_20250916201203_23_247.jpg #默认顶部图
#index_top_img_height: 800px #顶部图高度默认为整个视口

runtimeshow:
  enable: true
  publish_date: 24/5/2025

#页脚背景图
footer_img: /image/footer.jpg 

#背景图
background: /image/background.jpg

#文章封面
cover:    
  index_enable: true
  aside_enable: true
  archives_enable: true
  default_cover:

# 首页卡片布局
index_layout: 1

#本地搜索
local_search:
  enable: true
  # Preload the search data when the page loads.
  preload: false
  # Show top n results per article, show all results by setting to -1
  top_n_per_article: 1
  # Unescape html strings to the readable one.
  unescape: true

code_blocks:
  theme: light
#代码高度限制

highlight_height_limit: 200px
highlight_shrink: true

#logo
nav:
  # Navigation bar logo image
  logo: /image/b_396d2c65c6d973a43d310f09a53bcdb8.jpg
  display_title: true








# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://jasmine661.github.io
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: butterfly

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repository: git@github.com:Jasmine661/Jasmine661.github.io.git
  branch: main
